name: Validate Scripts

on: [push, pull_request]

jobs:
  validate-scripts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate Bash Scripts
      run: |
        # Check for syntax errors
        for script in $(find . -type f -name "*.sh"); do
          bash -n "$script"
        done

        # Use shellcheck to lint the scripts
        sudo apt-get install -y shellcheck
        shellcheck $(git ls-files '*.sh')

    - name: Check Bash Script Formatting
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install shfmt
      run: |
        pip install shfmt
        shfmt --version

    - name: Lint Bash Scripts
      run: |
        for script in $(git ls-files '*.sh'); do
          shfmt -d "$script"
        done

