name: Validate Scripts

on: [push, pull_request]

jobs:
  validate-scripts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate Bash Scripts
      run: |
        # Check for syntax errors
        for script in $(find . -type f -name "*.sh"); do
          bash -n "$script"
        done

        # Use shellcheck to lint the scripts
        sudo apt-get install -y shellcheck
        shellcheck $(git ls-files '*.sh')

    - name: Check Bash Script Formatting
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Prettier
      run: |
        npm install -g prettier

    - name: Lint Bash Scripts
      run: |
        prettier --check **/*.sh


